spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/dh-projeto-integrador?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:root}
    password: ${MUDA_EMAIL_PASSWORD:}

